# Generated by Django 5.2.4 on 2025-07-03 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_transcript', models.TextField()),
                ('corrected_transcript', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('duration_seconds', models.FloatField()),
                ('duration_formatted', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('keywords', models.TextField()),
                ('sentiment_analysis', models.JSONField(default=dict)),
                ('emotion_analysis', models.JSONField(default=dict)),
                ('content_assessment', models.JSONField(default=dict)),
                ('strengths_improvements', models.JSONField(default=dict)),
                ('repeated_words', models.JSONField(default=dict)),
                ('filler_words', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.transcript')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.FloatField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transcript',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.upload'),
        ),
    ]
